[package]
name = "Rocket-V"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
bitflags = "2.8.0"
clap = { version = "4.5.30", features = ["derive"] }
rustyline = "15.0.0"
rstest = "0.24.0"
device_tree = "1.1.0"